### ISSUE TITLE
timeout uploading result

### ISSUE THREAD

**Issue by Tom-Tom** [codecov/codecov-ruby#103]
Hi, i got a flaky test on circleci, with this error:

```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.2.11
==> Circle CI detected
==> Appending file network
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io
    query: token=secret&flags=backend&package=ruby-0.2.11&service=circleci&build=XXXXX&job=X&slug=XXXXXXX&pr&branch=XXXXX&commit=XXXXXXX
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags=backend&package=ruby-0.2.11&service=circleci&build=XXXXX&job=X&slug=XXXXXXXXXX&pr&branch=XXXXXXXXXX&commit=XXXXXXXX
->  Uploading to
<head><title>504 Gateway Time-out</title></head>
Traceback (most recent call last):
	11: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
	10: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov.rb:179:in `at_exit_behavior'
	 9: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov.rb:189:in `run_exit_tasks!'
	 8: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/configuration.rb:196:in `block in at_exit'
	 7: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/result.rb:51:in `format!'
	 6: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:470:in `format'
	 5: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:372:in `upload_to_codecov'
	 4: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:406:in `upload_to_v4'
	 3: from /usr/local/lib/ruby/2.7.0/uri/common.rb:737:in `URI'
	 2: from /usr/local/lib/ruby/2.7.0/uri/common.rb:234:in `parse'
	 1: from /usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:73:in `parse'
/usr/local/lib/ruby/2.7.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): "<head><title>504 Gateway Time-out</title></head>\\r\\n" (URI::InvalidURIError)

Exited with code exit status 1
CircleCI received exit code 1
```

A timeout error, the retries system does not seem to work properly
it happens sometime, not all the time.

Any idea how to fix this?

**Comment by thomasrockhu** [comment]
Hi @Tom-Tom, could you open a ticket in the support section of our [community boards](https://community.codecov.io) if this is still happening for you? We made an infrastructure change, and it's possible that this happened around that time.

**Comment by Tom-Tom** [comment]
Hello @thomasrockhu 

It's back

```
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.2.11
==> Circle CI detected
==> Appending file network
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io
    query: token=secret&flags=backend&package=ruby-0.2.11&service=circleci&build=189357&job=8&slug=XXXXXXX&pr&branch=XXXXXXX&commit=XXXXXXX
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags=backend&package=ruby-0.2.11&service=circleci&build=189357&job=8&slug=XXXXXXX&pr&branch=XXXXXXX&commit=XXXXXXX
->  Uploading to

Traceback (most recent call last):
	8: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/defaults.rb:27:in `block in <top (required)>'
	7: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov.rb:179:in `at_exit_behavior'
	6: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov.rb:189:in `run_exit_tasks!'
	5: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/configuration.rb:196:in `block in at_exit'
	4: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/simplecov-0.19.0/lib/simplecov/result.rb:51:in `format!'
	3: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:470:in `format'
	2: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:372:in `upload_to_codecov'
	1: from /home/circleci/livestorm/packages/backend/vendor/bundle/ruby/2.7.0/gems/codecov-0.2.11/lib/codecov.rb:406:in `upload_to_v4'
/usr/local/lib/ruby/2.7.0/uri/common.rb:739:in `URI': bad argument (expected URI object or URI string) (ArgumentError)

Exited with code exit status 1
CircleCI received exit code 1
```

I will check the community boards :)
