### ISSUE TITLE
Uploading report fails

### ISSUE THREAD

**Issue by tianhaoz95** [codecov/codecov-ruby#148]
```bash
  _____          _
 / ____|        | |
| |     ___   __| | ___  ___ _____   __
| |    / _ \ / _\`|/ _ \/ __/ _ \ \ / /
| |___| (_) | (_| |  __/ (_| (_) \ V /
 \_____\___/ \__,_|\___|\___\___/ \_/
                               Ruby-0.6.0
==> GitHub Actions detected
==> Gzipping contents
==> Uploading reports
    url:   https://codecov.io
    query: token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=fix%2Fmake-coverage-optional&pr=master&slug=tianhaoz95%2Ffastlane-plugin-flutter_version&build=1401940721&commit=30dd7cf8825a1a208c939f24b4839b3b80dba6b6
->  Pinging Codecov
https://codecov.io/upload/v4?token=secret&flags&package=ruby-0.6.0&service=github-actions&branch=fix%2Fmake-coverage-optional&pr=master&slug=tianhaoz95%2Ffastlane-plugin-flutter_version&build=1401940721&commit=30dd7cf8825a1a208c939f24b4839b3b80dba6b6
/home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/codecov-0.6.0/lib/codecov/uploader.rb:56:in `upload': Could not upload reports to Codecov (StandardError)
Invalid request parameters
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/codecov-0.6.0/lib/codecov.rb:15:in `format'
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/result.rb:51:in `format!'
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/configuration.rb:197:in `block in at_exit'
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:189:in `run_exit_tasks!'
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov.rb:179:in `at_exit_behavior'
	from /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/simplecov-0.21.2/lib/simplecov/defaults.rb:30:in `block in <top (required)>'
/opt/hostedtoolcache/Ruby/2.7.4/x64/bin/ruby -I/home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/lib:/home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/rspec-support-3.10.2/lib /home/runner/work/fastlane-plugin-flutter_version/fastlane-plugin-flutter_version/vendor/bundle/ruby/2.7.0/gems/rspec-core-3.10.1/exe/rspec --pattern spec/\*\*\{,/\*/\*\*\}/\*_spec.rb failed
Error: Process completed with exit code 1.
```

This happens around the time of 0.6.0, but reverting it didn't fix the issue, so I'm thinking if the paramter to the server has a breaking change?

See https://github.com/tianhaoz95/fastlane-plugin-flutter_version/runs/4054299473?check_suite_focus=true for the run and https://github.com/tianhaoz95/fastlane-plugin-flutter_version for source code

**Comment by AlexWayfer** [comment]
I suggest you to move to the new uploader: https://about.codecov.io/blog/codecov-uploader-deprecation-plan/

Discussion about migrating for Ruby: https://community.codecov.com/t/integration-new-beta-uploader-and-simplecov-ruby/3243
